//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orquestra3_SIAD.Orquestra_Instance {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.cryo.com.br/", ConfigurationName="Orquestra_Instance.InstanceSoap")]
    public interface InstanceSoap {
        
        // CODEGEN: Generating message contract since element name Token from namespace http://www.cryo.com.br/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cryo.com.br/CreateInstance01", ReplyAction="*")]
        Orquestra3_SIAD.Orquestra_Instance.CreateInstance01Response CreateInstance01(Orquestra3_SIAD.Orquestra_Instance.CreateInstance01Request request);
        
        // CODEGEN: Generating message contract since element name Token from namespace http://www.cryo.com.br/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cryo.com.br/CreateInstance02", ReplyAction="*")]
        Orquestra3_SIAD.Orquestra_Instance.CreateInstance02Response CreateInstance02(Orquestra3_SIAD.Orquestra_Instance.CreateInstance02Request request);
        
        // CODEGEN: Generating message contract since element name Token from namespace http://www.cryo.com.br/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cryo.com.br/CreateInstanceSubprocess01", ReplyAction="*")]
        Orquestra3_SIAD.Orquestra_Instance.CreateInstanceSubprocess01Response CreateInstanceSubprocess01(Orquestra3_SIAD.Orquestra_Instance.CreateInstanceSubprocess01Request request);
        
        // CODEGEN: Generating message contract since element name Token from namespace http://www.cryo.com.br/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cryo.com.br/Cancel01", ReplyAction="*")]
        Orquestra3_SIAD.Orquestra_Instance.Cancel01Response Cancel01(Orquestra3_SIAD.Orquestra_Instance.Cancel01Request request);
        
        // CODEGEN: Generating message contract since element name Token from namespace http://www.cryo.com.br/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cryo.com.br/Cancel02", ReplyAction="*")]
        Orquestra3_SIAD.Orquestra_Instance.Cancel02Response Cancel02(Orquestra3_SIAD.Orquestra_Instance.Cancel02Request request);
        
        // CODEGEN: Generating message contract since element name Token from namespace http://www.cryo.com.br/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cryo.com.br/GetXml01", ReplyAction="*")]
        Orquestra3_SIAD.Orquestra_Instance.GetXml01Response GetXml01(Orquestra3_SIAD.Orquestra_Instance.GetXml01Request request);
        
        // CODEGEN: Generating message contract since element name Token from namespace http://www.cryo.com.br/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cryo.com.br/UpdateForm01", ReplyAction="*")]
        Orquestra3_SIAD.Orquestra_Instance.UpdateForm01Response UpdateForm01(Orquestra3_SIAD.Orquestra_Instance.UpdateForm01Request request);
        
        // CODEGEN: Generating message contract since element name Token from namespace http://www.cryo.com.br/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cryo.com.br/FinalizeTask01", ReplyAction="*")]
        Orquestra3_SIAD.Orquestra_Instance.FinalizeTask01Response FinalizeTask01(Orquestra3_SIAD.Orquestra_Instance.FinalizeTask01Request request);
        
        // CODEGEN: Generating message contract since element name Token from namespace http://www.cryo.com.br/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cryo.com.br/FinalizeTask02", ReplyAction="*")]
        Orquestra3_SIAD.Orquestra_Instance.FinalizeTask02Response FinalizeTask02(Orquestra3_SIAD.Orquestra_Instance.FinalizeTask02Request request);
        
        // CODEGEN: Generating message contract since element name Token from namespace http://www.cryo.com.br/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cryo.com.br/FinalizeTask03", ReplyAction="*")]
        Orquestra3_SIAD.Orquestra_Instance.FinalizeTask03Response FinalizeTask03(Orquestra3_SIAD.Orquestra_Instance.FinalizeTask03Request request);
        
        // CODEGEN: Generating message contract since element name Token from namespace http://www.cryo.com.br/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cryo.com.br/FinalizeTask04", ReplyAction="*")]
        Orquestra3_SIAD.Orquestra_Instance.FinalizeTask04Response FinalizeTask04(Orquestra3_SIAD.Orquestra_Instance.FinalizeTask04Request request);
        
        // CODEGEN: Generating message contract since element name Token from namespace http://www.cryo.com.br/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cryo.com.br/AttachFile01", ReplyAction="*")]
        Orquestra3_SIAD.Orquestra_Instance.AttachFile01Response AttachFile01(Orquestra3_SIAD.Orquestra_Instance.AttachFile01Request request);
        
        // CODEGEN: Generating message contract since element name Token from namespace http://www.cryo.com.br/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cryo.com.br/AttachFile02", ReplyAction="*")]
        Orquestra3_SIAD.Orquestra_Instance.AttachFile02Response AttachFile02(Orquestra3_SIAD.Orquestra_Instance.AttachFile02Request request);
        
        // CODEGEN: Generating message contract since element name Token from namespace http://www.cryo.com.br/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cryo.com.br/AddMessage01", ReplyAction="*")]
        Orquestra3_SIAD.Orquestra_Instance.AddMessage01Response AddMessage01(Orquestra3_SIAD.Orquestra_Instance.AddMessage01Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateInstance01Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateInstance01", Namespace="http://www.cryo.com.br/", Order=0)]
        public Orquestra3_SIAD.Orquestra_Instance.CreateInstance01RequestBody Body;
        
        public CreateInstance01Request() {
        }
        
        public CreateInstance01Request(Orquestra3_SIAD.Orquestra_Instance.CreateInstance01RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cryo.com.br/")]
    public partial class CreateInstance01RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Token;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int CodFlow;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool Simulation;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string XmlValues;
        
        public CreateInstance01RequestBody() {
        }
        
        public CreateInstance01RequestBody(string Token, int CodFlow, bool Simulation, string XmlValues) {
            this.Token = Token;
            this.CodFlow = CodFlow;
            this.Simulation = Simulation;
            this.XmlValues = XmlValues;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateInstance01Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateInstance01Response", Namespace="http://www.cryo.com.br/", Order=0)]
        public Orquestra3_SIAD.Orquestra_Instance.CreateInstance01ResponseBody Body;
        
        public CreateInstance01Response() {
        }
        
        public CreateInstance01Response(Orquestra3_SIAD.Orquestra_Instance.CreateInstance01ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cryo.com.br/")]
    public partial class CreateInstance01ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement CreateInstance01Result;
        
        public CreateInstance01ResponseBody() {
        }
        
        public CreateInstance01ResponseBody(System.Xml.Linq.XElement CreateInstance01Result) {
            this.CreateInstance01Result = CreateInstance01Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateInstance02Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateInstance02", Namespace="http://www.cryo.com.br/", Order=0)]
        public Orquestra3_SIAD.Orquestra_Instance.CreateInstance02RequestBody Body;
        
        public CreateInstance02Request() {
        }
        
        public CreateInstance02Request(Orquestra3_SIAD.Orquestra_Instance.CreateInstance02RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cryo.com.br/")]
    public partial class CreateInstance02RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Token;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int CodArea;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int CodPosition;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int CodFlow;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool Simulation;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string XmlValues;
        
        public CreateInstance02RequestBody() {
        }
        
        public CreateInstance02RequestBody(string Token, int CodArea, int CodPosition, int CodFlow, bool Simulation, string XmlValues) {
            this.Token = Token;
            this.CodArea = CodArea;
            this.CodPosition = CodPosition;
            this.CodFlow = CodFlow;
            this.Simulation = Simulation;
            this.XmlValues = XmlValues;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateInstance02Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateInstance02Response", Namespace="http://www.cryo.com.br/", Order=0)]
        public Orquestra3_SIAD.Orquestra_Instance.CreateInstance02ResponseBody Body;
        
        public CreateInstance02Response() {
        }
        
        public CreateInstance02Response(Orquestra3_SIAD.Orquestra_Instance.CreateInstance02ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cryo.com.br/")]
    public partial class CreateInstance02ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement CreateInstance02Result;
        
        public CreateInstance02ResponseBody() {
        }
        
        public CreateInstance02ResponseBody(System.Xml.Linq.XElement CreateInstance02Result) {
            this.CreateInstance02Result = CreateInstance02Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateInstanceSubprocess01Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateInstanceSubprocess01", Namespace="http://www.cryo.com.br/", Order=0)]
        public Orquestra3_SIAD.Orquestra_Instance.CreateInstanceSubprocess01RequestBody Body;
        
        public CreateInstanceSubprocess01Request() {
        }
        
        public CreateInstanceSubprocess01Request(Orquestra3_SIAD.Orquestra_Instance.CreateInstanceSubprocess01RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cryo.com.br/")]
    public partial class CreateInstanceSubprocess01RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Token;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int CodFlowSubprocess;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool Simulation;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string XmlValues;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int CodFlowParent;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int CodFlowExecuteParent;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string DsFlowElementAlias;
        
        public CreateInstanceSubprocess01RequestBody() {
        }
        
        public CreateInstanceSubprocess01RequestBody(string Token, int CodFlowSubprocess, bool Simulation, string XmlValues, int CodFlowParent, int CodFlowExecuteParent, string DsFlowElementAlias) {
            this.Token = Token;
            this.CodFlowSubprocess = CodFlowSubprocess;
            this.Simulation = Simulation;
            this.XmlValues = XmlValues;
            this.CodFlowParent = CodFlowParent;
            this.CodFlowExecuteParent = CodFlowExecuteParent;
            this.DsFlowElementAlias = DsFlowElementAlias;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateInstanceSubprocess01Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateInstanceSubprocess01Response", Namespace="http://www.cryo.com.br/", Order=0)]
        public Orquestra3_SIAD.Orquestra_Instance.CreateInstanceSubprocess01ResponseBody Body;
        
        public CreateInstanceSubprocess01Response() {
        }
        
        public CreateInstanceSubprocess01Response(Orquestra3_SIAD.Orquestra_Instance.CreateInstanceSubprocess01ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cryo.com.br/")]
    public partial class CreateInstanceSubprocess01ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement CreateInstanceSubprocess01Result;
        
        public CreateInstanceSubprocess01ResponseBody() {
        }
        
        public CreateInstanceSubprocess01ResponseBody(System.Xml.Linq.XElement CreateInstanceSubprocess01Result) {
            this.CreateInstanceSubprocess01Result = CreateInstanceSubprocess01Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Cancel01Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Cancel01", Namespace="http://www.cryo.com.br/", Order=0)]
        public Orquestra3_SIAD.Orquestra_Instance.Cancel01RequestBody Body;
        
        public Cancel01Request() {
        }
        
        public Cancel01Request(Orquestra3_SIAD.Orquestra_Instance.Cancel01RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cryo.com.br/")]
    public partial class Cancel01RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Token;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int CodFlowExecute;
        
        public Cancel01RequestBody() {
        }
        
        public Cancel01RequestBody(string Token, int CodFlowExecute) {
            this.Token = Token;
            this.CodFlowExecute = CodFlowExecute;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Cancel01Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Cancel01Response", Namespace="http://www.cryo.com.br/", Order=0)]
        public Orquestra3_SIAD.Orquestra_Instance.Cancel01ResponseBody Body;
        
        public Cancel01Response() {
        }
        
        public Cancel01Response(Orquestra3_SIAD.Orquestra_Instance.Cancel01ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cryo.com.br/")]
    public partial class Cancel01ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement Cancel01Result;
        
        public Cancel01ResponseBody() {
        }
        
        public Cancel01ResponseBody(System.Xml.Linq.XElement Cancel01Result) {
            this.Cancel01Result = Cancel01Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Cancel02Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Cancel02", Namespace="http://www.cryo.com.br/", Order=0)]
        public Orquestra3_SIAD.Orquestra_Instance.Cancel02RequestBody Body;
        
        public Cancel02Request() {
        }
        
        public Cancel02Request(Orquestra3_SIAD.Orquestra_Instance.Cancel02RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cryo.com.br/")]
    public partial class Cancel02RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Token;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int CodFlowExecute;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DsObs;
        
        public Cancel02RequestBody() {
        }
        
        public Cancel02RequestBody(string Token, int CodFlowExecute, string DsObs) {
            this.Token = Token;
            this.CodFlowExecute = CodFlowExecute;
            this.DsObs = DsObs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Cancel02Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Cancel02Response", Namespace="http://www.cryo.com.br/", Order=0)]
        public Orquestra3_SIAD.Orquestra_Instance.Cancel02ResponseBody Body;
        
        public Cancel02Response() {
        }
        
        public Cancel02Response(Orquestra3_SIAD.Orquestra_Instance.Cancel02ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cryo.com.br/")]
    public partial class Cancel02ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement Cancel02Result;
        
        public Cancel02ResponseBody() {
        }
        
        public Cancel02ResponseBody(System.Xml.Linq.XElement Cancel02Result) {
            this.Cancel02Result = Cancel02Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetXml01Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetXml01", Namespace="http://www.cryo.com.br/", Order=0)]
        public Orquestra3_SIAD.Orquestra_Instance.GetXml01RequestBody Body;
        
        public GetXml01Request() {
        }
        
        public GetXml01Request(Orquestra3_SIAD.Orquestra_Instance.GetXml01RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cryo.com.br/")]
    public partial class GetXml01RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Token;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int CodFlowExecute;
        
        public GetXml01RequestBody() {
        }
        
        public GetXml01RequestBody(string Token, int CodFlowExecute) {
            this.Token = Token;
            this.CodFlowExecute = CodFlowExecute;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetXml01Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetXml01Response", Namespace="http://www.cryo.com.br/", Order=0)]
        public Orquestra3_SIAD.Orquestra_Instance.GetXml01ResponseBody Body;
        
        public GetXml01Response() {
        }
        
        public GetXml01Response(Orquestra3_SIAD.Orquestra_Instance.GetXml01ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cryo.com.br/")]
    public partial class GetXml01ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetXml01Result;
        
        public GetXml01ResponseBody() {
        }
        
        public GetXml01ResponseBody(System.Xml.Linq.XElement GetXml01Result) {
            this.GetXml01Result = GetXml01Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateForm01Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateForm01", Namespace="http://www.cryo.com.br/", Order=0)]
        public Orquestra3_SIAD.Orquestra_Instance.UpdateForm01RequestBody Body;
        
        public UpdateForm01Request() {
        }
        
        public UpdateForm01Request(Orquestra3_SIAD.Orquestra_Instance.UpdateForm01RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cryo.com.br/")]
    public partial class UpdateForm01RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Token;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int CodFlowExecute;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string XmlValues;
        
        public UpdateForm01RequestBody() {
        }
        
        public UpdateForm01RequestBody(string Token, int CodFlowExecute, string XmlValues) {
            this.Token = Token;
            this.CodFlowExecute = CodFlowExecute;
            this.XmlValues = XmlValues;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateForm01Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateForm01Response", Namespace="http://www.cryo.com.br/", Order=0)]
        public Orquestra3_SIAD.Orquestra_Instance.UpdateForm01ResponseBody Body;
        
        public UpdateForm01Response() {
        }
        
        public UpdateForm01Response(Orquestra3_SIAD.Orquestra_Instance.UpdateForm01ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cryo.com.br/")]
    public partial class UpdateForm01ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement UpdateForm01Result;
        
        public UpdateForm01ResponseBody() {
        }
        
        public UpdateForm01ResponseBody(System.Xml.Linq.XElement UpdateForm01Result) {
            this.UpdateForm01Result = UpdateForm01Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FinalizeTask01Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FinalizeTask01", Namespace="http://www.cryo.com.br/", Order=0)]
        public Orquestra3_SIAD.Orquestra_Instance.FinalizeTask01RequestBody Body;
        
        public FinalizeTask01Request() {
        }
        
        public FinalizeTask01Request(Orquestra3_SIAD.Orquestra_Instance.FinalizeTask01RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cryo.com.br/")]
    public partial class FinalizeTask01RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Token;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int CodFlowExecuteTask;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int CodFlowResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string XmlValues;
        
        public FinalizeTask01RequestBody() {
        }
        
        public FinalizeTask01RequestBody(string Token, int CodFlowExecuteTask, int CodFlowResult, string XmlValues) {
            this.Token = Token;
            this.CodFlowExecuteTask = CodFlowExecuteTask;
            this.CodFlowResult = CodFlowResult;
            this.XmlValues = XmlValues;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FinalizeTask01Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FinalizeTask01Response", Namespace="http://www.cryo.com.br/", Order=0)]
        public Orquestra3_SIAD.Orquestra_Instance.FinalizeTask01ResponseBody Body;
        
        public FinalizeTask01Response() {
        }
        
        public FinalizeTask01Response(Orquestra3_SIAD.Orquestra_Instance.FinalizeTask01ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cryo.com.br/")]
    public partial class FinalizeTask01ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement FinalizeTask01Result;
        
        public FinalizeTask01ResponseBody() {
        }
        
        public FinalizeTask01ResponseBody(System.Xml.Linq.XElement FinalizeTask01Result) {
            this.FinalizeTask01Result = FinalizeTask01Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FinalizeTask02Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FinalizeTask02", Namespace="http://www.cryo.com.br/", Order=0)]
        public Orquestra3_SIAD.Orquestra_Instance.FinalizeTask02RequestBody Body;
        
        public FinalizeTask02Request() {
        }
        
        public FinalizeTask02Request(Orquestra3_SIAD.Orquestra_Instance.FinalizeTask02RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cryo.com.br/")]
    public partial class FinalizeTask02RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Token;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int CodFlowExecuteTask;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DsFlowResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string XmlValues;
        
        public FinalizeTask02RequestBody() {
        }
        
        public FinalizeTask02RequestBody(string Token, int CodFlowExecuteTask, string DsFlowResult, string XmlValues) {
            this.Token = Token;
            this.CodFlowExecuteTask = CodFlowExecuteTask;
            this.DsFlowResult = DsFlowResult;
            this.XmlValues = XmlValues;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FinalizeTask02Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FinalizeTask02Response", Namespace="http://www.cryo.com.br/", Order=0)]
        public Orquestra3_SIAD.Orquestra_Instance.FinalizeTask02ResponseBody Body;
        
        public FinalizeTask02Response() {
        }
        
        public FinalizeTask02Response(Orquestra3_SIAD.Orquestra_Instance.FinalizeTask02ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cryo.com.br/")]
    public partial class FinalizeTask02ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement FinalizeTask02Result;
        
        public FinalizeTask02ResponseBody() {
        }
        
        public FinalizeTask02ResponseBody(System.Xml.Linq.XElement FinalizeTask02Result) {
            this.FinalizeTask02Result = FinalizeTask02Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FinalizeTask03Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FinalizeTask03", Namespace="http://www.cryo.com.br/", Order=0)]
        public Orquestra3_SIAD.Orquestra_Instance.FinalizeTask03RequestBody Body;
        
        public FinalizeTask03Request() {
        }
        
        public FinalizeTask03Request(Orquestra3_SIAD.Orquestra_Instance.FinalizeTask03RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cryo.com.br/")]
    public partial class FinalizeTask03RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Token;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int CodFlowExecute;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DsFlowElementAlias;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int CodFlowResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string XmlValues;
        
        public FinalizeTask03RequestBody() {
        }
        
        public FinalizeTask03RequestBody(string Token, int CodFlowExecute, string DsFlowElementAlias, int CodFlowResult, string XmlValues) {
            this.Token = Token;
            this.CodFlowExecute = CodFlowExecute;
            this.DsFlowElementAlias = DsFlowElementAlias;
            this.CodFlowResult = CodFlowResult;
            this.XmlValues = XmlValues;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FinalizeTask03Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FinalizeTask03Response", Namespace="http://www.cryo.com.br/", Order=0)]
        public Orquestra3_SIAD.Orquestra_Instance.FinalizeTask03ResponseBody Body;
        
        public FinalizeTask03Response() {
        }
        
        public FinalizeTask03Response(Orquestra3_SIAD.Orquestra_Instance.FinalizeTask03ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cryo.com.br/")]
    public partial class FinalizeTask03ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement FinalizeTask03Result;
        
        public FinalizeTask03ResponseBody() {
        }
        
        public FinalizeTask03ResponseBody(System.Xml.Linq.XElement FinalizeTask03Result) {
            this.FinalizeTask03Result = FinalizeTask03Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FinalizeTask04Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FinalizeTask04", Namespace="http://www.cryo.com.br/", Order=0)]
        public Orquestra3_SIAD.Orquestra_Instance.FinalizeTask04RequestBody Body;
        
        public FinalizeTask04Request() {
        }
        
        public FinalizeTask04Request(Orquestra3_SIAD.Orquestra_Instance.FinalizeTask04RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cryo.com.br/")]
    public partial class FinalizeTask04RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Token;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int CodFlowExecute;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DsFlowElementAlias;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DsFlowResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string XmlValues;
        
        public FinalizeTask04RequestBody() {
        }
        
        public FinalizeTask04RequestBody(string Token, int CodFlowExecute, string DsFlowElementAlias, string DsFlowResult, string XmlValues) {
            this.Token = Token;
            this.CodFlowExecute = CodFlowExecute;
            this.DsFlowElementAlias = DsFlowElementAlias;
            this.DsFlowResult = DsFlowResult;
            this.XmlValues = XmlValues;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FinalizeTask04Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FinalizeTask04Response", Namespace="http://www.cryo.com.br/", Order=0)]
        public Orquestra3_SIAD.Orquestra_Instance.FinalizeTask04ResponseBody Body;
        
        public FinalizeTask04Response() {
        }
        
        public FinalizeTask04Response(Orquestra3_SIAD.Orquestra_Instance.FinalizeTask04ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cryo.com.br/")]
    public partial class FinalizeTask04ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement FinalizeTask04Result;
        
        public FinalizeTask04ResponseBody() {
        }
        
        public FinalizeTask04ResponseBody(System.Xml.Linq.XElement FinalizeTask04Result) {
            this.FinalizeTask04Result = FinalizeTask04Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AttachFile01Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AttachFile01", Namespace="http://www.cryo.com.br/", Order=0)]
        public Orquestra3_SIAD.Orquestra_Instance.AttachFile01RequestBody Body;
        
        public AttachFile01Request() {
        }
        
        public AttachFile01Request(Orquestra3_SIAD.Orquestra_Instance.AttachFile01RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cryo.com.br/")]
    public partial class AttachFile01RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Token;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int CodFlowExecuteTask;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DsFileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DsFilePath;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DsResume;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool RequesterCanSee;
        
        public AttachFile01RequestBody() {
        }
        
        public AttachFile01RequestBody(string Token, int CodFlowExecuteTask, string DsFileName, string DsFilePath, string DsResume, bool RequesterCanSee) {
            this.Token = Token;
            this.CodFlowExecuteTask = CodFlowExecuteTask;
            this.DsFileName = DsFileName;
            this.DsFilePath = DsFilePath;
            this.DsResume = DsResume;
            this.RequesterCanSee = RequesterCanSee;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AttachFile01Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AttachFile01Response", Namespace="http://www.cryo.com.br/", Order=0)]
        public Orquestra3_SIAD.Orquestra_Instance.AttachFile01ResponseBody Body;
        
        public AttachFile01Response() {
        }
        
        public AttachFile01Response(Orquestra3_SIAD.Orquestra_Instance.AttachFile01ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cryo.com.br/")]
    public partial class AttachFile01ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement AttachFile01Result;
        
        public AttachFile01ResponseBody() {
        }
        
        public AttachFile01ResponseBody(System.Xml.Linq.XElement AttachFile01Result) {
            this.AttachFile01Result = AttachFile01Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AttachFile02Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AttachFile02", Namespace="http://www.cryo.com.br/", Order=0)]
        public Orquestra3_SIAD.Orquestra_Instance.AttachFile02RequestBody Body;
        
        public AttachFile02Request() {
        }
        
        public AttachFile02Request(Orquestra3_SIAD.Orquestra_Instance.AttachFile02RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cryo.com.br/")]
    public partial class AttachFile02RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Token;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int CodFlowExecute;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DsFlowElementAlias;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DsFileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DsFilePath;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string DsResume;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool RequesterCanSee;
        
        public AttachFile02RequestBody() {
        }
        
        public AttachFile02RequestBody(string Token, int CodFlowExecute, string DsFlowElementAlias, string DsFileName, string DsFilePath, string DsResume, bool RequesterCanSee) {
            this.Token = Token;
            this.CodFlowExecute = CodFlowExecute;
            this.DsFlowElementAlias = DsFlowElementAlias;
            this.DsFileName = DsFileName;
            this.DsFilePath = DsFilePath;
            this.DsResume = DsResume;
            this.RequesterCanSee = RequesterCanSee;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AttachFile02Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AttachFile02Response", Namespace="http://www.cryo.com.br/", Order=0)]
        public Orquestra3_SIAD.Orquestra_Instance.AttachFile02ResponseBody Body;
        
        public AttachFile02Response() {
        }
        
        public AttachFile02Response(Orquestra3_SIAD.Orquestra_Instance.AttachFile02ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cryo.com.br/")]
    public partial class AttachFile02ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement AttachFile02Result;
        
        public AttachFile02ResponseBody() {
        }
        
        public AttachFile02ResponseBody(System.Xml.Linq.XElement AttachFile02Result) {
            this.AttachFile02Result = AttachFile02Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddMessage01Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddMessage01", Namespace="http://www.cryo.com.br/", Order=0)]
        public Orquestra3_SIAD.Orquestra_Instance.AddMessage01RequestBody Body;
        
        public AddMessage01Request() {
        }
        
        public AddMessage01Request(Orquestra3_SIAD.Orquestra_Instance.AddMessage01RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cryo.com.br/")]
    public partial class AddMessage01RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Token;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int CodFlowExecuteTask;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DsMessage;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool RequesterCanSee;
        
        public AddMessage01RequestBody() {
        }
        
        public AddMessage01RequestBody(string Token, int CodFlowExecuteTask, string DsMessage, bool RequesterCanSee) {
            this.Token = Token;
            this.CodFlowExecuteTask = CodFlowExecuteTask;
            this.DsMessage = DsMessage;
            this.RequesterCanSee = RequesterCanSee;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddMessage01Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddMessage01Response", Namespace="http://www.cryo.com.br/", Order=0)]
        public Orquestra3_SIAD.Orquestra_Instance.AddMessage01ResponseBody Body;
        
        public AddMessage01Response() {
        }
        
        public AddMessage01Response(Orquestra3_SIAD.Orquestra_Instance.AddMessage01ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cryo.com.br/")]
    public partial class AddMessage01ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement AddMessage01Result;
        
        public AddMessage01ResponseBody() {
        }
        
        public AddMessage01ResponseBody(System.Xml.Linq.XElement AddMessage01Result) {
            this.AddMessage01Result = AddMessage01Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InstanceSoapChannel : Orquestra3_SIAD.Orquestra_Instance.InstanceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InstanceSoapClient : System.ServiceModel.ClientBase<Orquestra3_SIAD.Orquestra_Instance.InstanceSoap>, Orquestra3_SIAD.Orquestra_Instance.InstanceSoap {
        
        public InstanceSoapClient() {
        }
        
        public InstanceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InstanceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InstanceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InstanceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Orquestra3_SIAD.Orquestra_Instance.CreateInstance01Response Orquestra3_SIAD.Orquestra_Instance.InstanceSoap.CreateInstance01(Orquestra3_SIAD.Orquestra_Instance.CreateInstance01Request request) {
            return base.Channel.CreateInstance01(request);
        }
        
        public System.Xml.Linq.XElement CreateInstance01(string Token, int CodFlow, bool Simulation, string XmlValues) {
            Orquestra3_SIAD.Orquestra_Instance.CreateInstance01Request inValue = new Orquestra3_SIAD.Orquestra_Instance.CreateInstance01Request();
            inValue.Body = new Orquestra3_SIAD.Orquestra_Instance.CreateInstance01RequestBody();
            inValue.Body.Token = Token;
            inValue.Body.CodFlow = CodFlow;
            inValue.Body.Simulation = Simulation;
            inValue.Body.XmlValues = XmlValues;
            Orquestra3_SIAD.Orquestra_Instance.CreateInstance01Response retVal = ((Orquestra3_SIAD.Orquestra_Instance.InstanceSoap)(this)).CreateInstance01(inValue);
            return retVal.Body.CreateInstance01Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Orquestra3_SIAD.Orquestra_Instance.CreateInstance02Response Orquestra3_SIAD.Orquestra_Instance.InstanceSoap.CreateInstance02(Orquestra3_SIAD.Orquestra_Instance.CreateInstance02Request request) {
            return base.Channel.CreateInstance02(request);
        }
        
        public System.Xml.Linq.XElement CreateInstance02(string Token, int CodArea, int CodPosition, int CodFlow, bool Simulation, string XmlValues) {
            Orquestra3_SIAD.Orquestra_Instance.CreateInstance02Request inValue = new Orquestra3_SIAD.Orquestra_Instance.CreateInstance02Request();
            inValue.Body = new Orquestra3_SIAD.Orquestra_Instance.CreateInstance02RequestBody();
            inValue.Body.Token = Token;
            inValue.Body.CodArea = CodArea;
            inValue.Body.CodPosition = CodPosition;
            inValue.Body.CodFlow = CodFlow;
            inValue.Body.Simulation = Simulation;
            inValue.Body.XmlValues = XmlValues;
            Orquestra3_SIAD.Orquestra_Instance.CreateInstance02Response retVal = ((Orquestra3_SIAD.Orquestra_Instance.InstanceSoap)(this)).CreateInstance02(inValue);
            return retVal.Body.CreateInstance02Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Orquestra3_SIAD.Orquestra_Instance.CreateInstanceSubprocess01Response Orquestra3_SIAD.Orquestra_Instance.InstanceSoap.CreateInstanceSubprocess01(Orquestra3_SIAD.Orquestra_Instance.CreateInstanceSubprocess01Request request) {
            return base.Channel.CreateInstanceSubprocess01(request);
        }
        
        public System.Xml.Linq.XElement CreateInstanceSubprocess01(string Token, int CodFlowSubprocess, bool Simulation, string XmlValues, int CodFlowParent, int CodFlowExecuteParent, string DsFlowElementAlias) {
            Orquestra3_SIAD.Orquestra_Instance.CreateInstanceSubprocess01Request inValue = new Orquestra3_SIAD.Orquestra_Instance.CreateInstanceSubprocess01Request();
            inValue.Body = new Orquestra3_SIAD.Orquestra_Instance.CreateInstanceSubprocess01RequestBody();
            inValue.Body.Token = Token;
            inValue.Body.CodFlowSubprocess = CodFlowSubprocess;
            inValue.Body.Simulation = Simulation;
            inValue.Body.XmlValues = XmlValues;
            inValue.Body.CodFlowParent = CodFlowParent;
            inValue.Body.CodFlowExecuteParent = CodFlowExecuteParent;
            inValue.Body.DsFlowElementAlias = DsFlowElementAlias;
            Orquestra3_SIAD.Orquestra_Instance.CreateInstanceSubprocess01Response retVal = ((Orquestra3_SIAD.Orquestra_Instance.InstanceSoap)(this)).CreateInstanceSubprocess01(inValue);
            return retVal.Body.CreateInstanceSubprocess01Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Orquestra3_SIAD.Orquestra_Instance.Cancel01Response Orquestra3_SIAD.Orquestra_Instance.InstanceSoap.Cancel01(Orquestra3_SIAD.Orquestra_Instance.Cancel01Request request) {
            return base.Channel.Cancel01(request);
        }
        
        public System.Xml.Linq.XElement Cancel01(string Token, int CodFlowExecute) {
            Orquestra3_SIAD.Orquestra_Instance.Cancel01Request inValue = new Orquestra3_SIAD.Orquestra_Instance.Cancel01Request();
            inValue.Body = new Orquestra3_SIAD.Orquestra_Instance.Cancel01RequestBody();
            inValue.Body.Token = Token;
            inValue.Body.CodFlowExecute = CodFlowExecute;
            Orquestra3_SIAD.Orquestra_Instance.Cancel01Response retVal = ((Orquestra3_SIAD.Orquestra_Instance.InstanceSoap)(this)).Cancel01(inValue);
            return retVal.Body.Cancel01Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Orquestra3_SIAD.Orquestra_Instance.Cancel02Response Orquestra3_SIAD.Orquestra_Instance.InstanceSoap.Cancel02(Orquestra3_SIAD.Orquestra_Instance.Cancel02Request request) {
            return base.Channel.Cancel02(request);
        }
        
        public System.Xml.Linq.XElement Cancel02(string Token, int CodFlowExecute, string DsObs) {
            Orquestra3_SIAD.Orquestra_Instance.Cancel02Request inValue = new Orquestra3_SIAD.Orquestra_Instance.Cancel02Request();
            inValue.Body = new Orquestra3_SIAD.Orquestra_Instance.Cancel02RequestBody();
            inValue.Body.Token = Token;
            inValue.Body.CodFlowExecute = CodFlowExecute;
            inValue.Body.DsObs = DsObs;
            Orquestra3_SIAD.Orquestra_Instance.Cancel02Response retVal = ((Orquestra3_SIAD.Orquestra_Instance.InstanceSoap)(this)).Cancel02(inValue);
            return retVal.Body.Cancel02Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Orquestra3_SIAD.Orquestra_Instance.GetXml01Response Orquestra3_SIAD.Orquestra_Instance.InstanceSoap.GetXml01(Orquestra3_SIAD.Orquestra_Instance.GetXml01Request request) {
            return base.Channel.GetXml01(request);
        }
        
        public System.Xml.Linq.XElement GetXml01(string Token, int CodFlowExecute) {
            Orquestra3_SIAD.Orquestra_Instance.GetXml01Request inValue = new Orquestra3_SIAD.Orquestra_Instance.GetXml01Request();
            inValue.Body = new Orquestra3_SIAD.Orquestra_Instance.GetXml01RequestBody();
            inValue.Body.Token = Token;
            inValue.Body.CodFlowExecute = CodFlowExecute;
            Orquestra3_SIAD.Orquestra_Instance.GetXml01Response retVal = ((Orquestra3_SIAD.Orquestra_Instance.InstanceSoap)(this)).GetXml01(inValue);
            return retVal.Body.GetXml01Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Orquestra3_SIAD.Orquestra_Instance.UpdateForm01Response Orquestra3_SIAD.Orquestra_Instance.InstanceSoap.UpdateForm01(Orquestra3_SIAD.Orquestra_Instance.UpdateForm01Request request) {
            return base.Channel.UpdateForm01(request);
        }
        
        public System.Xml.Linq.XElement UpdateForm01(string Token, int CodFlowExecute, string XmlValues) {
            Orquestra3_SIAD.Orquestra_Instance.UpdateForm01Request inValue = new Orquestra3_SIAD.Orquestra_Instance.UpdateForm01Request();
            inValue.Body = new Orquestra3_SIAD.Orquestra_Instance.UpdateForm01RequestBody();
            inValue.Body.Token = Token;
            inValue.Body.CodFlowExecute = CodFlowExecute;
            inValue.Body.XmlValues = XmlValues;
            Orquestra3_SIAD.Orquestra_Instance.UpdateForm01Response retVal = ((Orquestra3_SIAD.Orquestra_Instance.InstanceSoap)(this)).UpdateForm01(inValue);
            return retVal.Body.UpdateForm01Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Orquestra3_SIAD.Orquestra_Instance.FinalizeTask01Response Orquestra3_SIAD.Orquestra_Instance.InstanceSoap.FinalizeTask01(Orquestra3_SIAD.Orquestra_Instance.FinalizeTask01Request request) {
            return base.Channel.FinalizeTask01(request);
        }
        
        public System.Xml.Linq.XElement FinalizeTask01(string Token, int CodFlowExecuteTask, int CodFlowResult, string XmlValues) {
            Orquestra3_SIAD.Orquestra_Instance.FinalizeTask01Request inValue = new Orquestra3_SIAD.Orquestra_Instance.FinalizeTask01Request();
            inValue.Body = new Orquestra3_SIAD.Orquestra_Instance.FinalizeTask01RequestBody();
            inValue.Body.Token = Token;
            inValue.Body.CodFlowExecuteTask = CodFlowExecuteTask;
            inValue.Body.CodFlowResult = CodFlowResult;
            inValue.Body.XmlValues = XmlValues;
            Orquestra3_SIAD.Orquestra_Instance.FinalizeTask01Response retVal = ((Orquestra3_SIAD.Orquestra_Instance.InstanceSoap)(this)).FinalizeTask01(inValue);
            return retVal.Body.FinalizeTask01Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Orquestra3_SIAD.Orquestra_Instance.FinalizeTask02Response Orquestra3_SIAD.Orquestra_Instance.InstanceSoap.FinalizeTask02(Orquestra3_SIAD.Orquestra_Instance.FinalizeTask02Request request) {
            return base.Channel.FinalizeTask02(request);
        }
        
        public System.Xml.Linq.XElement FinalizeTask02(string Token, int CodFlowExecuteTask, string DsFlowResult, string XmlValues) {
            Orquestra3_SIAD.Orquestra_Instance.FinalizeTask02Request inValue = new Orquestra3_SIAD.Orquestra_Instance.FinalizeTask02Request();
            inValue.Body = new Orquestra3_SIAD.Orquestra_Instance.FinalizeTask02RequestBody();
            inValue.Body.Token = Token;
            inValue.Body.CodFlowExecuteTask = CodFlowExecuteTask;
            inValue.Body.DsFlowResult = DsFlowResult;
            inValue.Body.XmlValues = XmlValues;
            Orquestra3_SIAD.Orquestra_Instance.FinalizeTask02Response retVal = ((Orquestra3_SIAD.Orquestra_Instance.InstanceSoap)(this)).FinalizeTask02(inValue);
            return retVal.Body.FinalizeTask02Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Orquestra3_SIAD.Orquestra_Instance.FinalizeTask03Response Orquestra3_SIAD.Orquestra_Instance.InstanceSoap.FinalizeTask03(Orquestra3_SIAD.Orquestra_Instance.FinalizeTask03Request request) {
            return base.Channel.FinalizeTask03(request);
        }
        
        public System.Xml.Linq.XElement FinalizeTask03(string Token, int CodFlowExecute, string DsFlowElementAlias, int CodFlowResult, string XmlValues) {
            Orquestra3_SIAD.Orquestra_Instance.FinalizeTask03Request inValue = new Orquestra3_SIAD.Orquestra_Instance.FinalizeTask03Request();
            inValue.Body = new Orquestra3_SIAD.Orquestra_Instance.FinalizeTask03RequestBody();
            inValue.Body.Token = Token;
            inValue.Body.CodFlowExecute = CodFlowExecute;
            inValue.Body.DsFlowElementAlias = DsFlowElementAlias;
            inValue.Body.CodFlowResult = CodFlowResult;
            inValue.Body.XmlValues = XmlValues;
            Orquestra3_SIAD.Orquestra_Instance.FinalizeTask03Response retVal = ((Orquestra3_SIAD.Orquestra_Instance.InstanceSoap)(this)).FinalizeTask03(inValue);
            return retVal.Body.FinalizeTask03Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Orquestra3_SIAD.Orquestra_Instance.FinalizeTask04Response Orquestra3_SIAD.Orquestra_Instance.InstanceSoap.FinalizeTask04(Orquestra3_SIAD.Orquestra_Instance.FinalizeTask04Request request) {
            return base.Channel.FinalizeTask04(request);
        }
        
        public System.Xml.Linq.XElement FinalizeTask04(string Token, int CodFlowExecute, string DsFlowElementAlias, string DsFlowResult, string XmlValues) {
            Orquestra3_SIAD.Orquestra_Instance.FinalizeTask04Request inValue = new Orquestra3_SIAD.Orquestra_Instance.FinalizeTask04Request();
            inValue.Body = new Orquestra3_SIAD.Orquestra_Instance.FinalizeTask04RequestBody();
            inValue.Body.Token = Token;
            inValue.Body.CodFlowExecute = CodFlowExecute;
            inValue.Body.DsFlowElementAlias = DsFlowElementAlias;
            inValue.Body.DsFlowResult = DsFlowResult;
            inValue.Body.XmlValues = XmlValues;
            Orquestra3_SIAD.Orquestra_Instance.FinalizeTask04Response retVal = ((Orquestra3_SIAD.Orquestra_Instance.InstanceSoap)(this)).FinalizeTask04(inValue);
            return retVal.Body.FinalizeTask04Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Orquestra3_SIAD.Orquestra_Instance.AttachFile01Response Orquestra3_SIAD.Orquestra_Instance.InstanceSoap.AttachFile01(Orquestra3_SIAD.Orquestra_Instance.AttachFile01Request request) {
            return base.Channel.AttachFile01(request);
        }
        
        public System.Xml.Linq.XElement AttachFile01(string Token, int CodFlowExecuteTask, string DsFileName, string DsFilePath, string DsResume, bool RequesterCanSee) {
            Orquestra3_SIAD.Orquestra_Instance.AttachFile01Request inValue = new Orquestra3_SIAD.Orquestra_Instance.AttachFile01Request();
            inValue.Body = new Orquestra3_SIAD.Orquestra_Instance.AttachFile01RequestBody();
            inValue.Body.Token = Token;
            inValue.Body.CodFlowExecuteTask = CodFlowExecuteTask;
            inValue.Body.DsFileName = DsFileName;
            inValue.Body.DsFilePath = DsFilePath;
            inValue.Body.DsResume = DsResume;
            inValue.Body.RequesterCanSee = RequesterCanSee;
            Orquestra3_SIAD.Orquestra_Instance.AttachFile01Response retVal = ((Orquestra3_SIAD.Orquestra_Instance.InstanceSoap)(this)).AttachFile01(inValue);
            return retVal.Body.AttachFile01Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Orquestra3_SIAD.Orquestra_Instance.AttachFile02Response Orquestra3_SIAD.Orquestra_Instance.InstanceSoap.AttachFile02(Orquestra3_SIAD.Orquestra_Instance.AttachFile02Request request) {
            return base.Channel.AttachFile02(request);
        }
        
        public System.Xml.Linq.XElement AttachFile02(string Token, int CodFlowExecute, string DsFlowElementAlias, string DsFileName, string DsFilePath, string DsResume, bool RequesterCanSee) {
            Orquestra3_SIAD.Orquestra_Instance.AttachFile02Request inValue = new Orquestra3_SIAD.Orquestra_Instance.AttachFile02Request();
            inValue.Body = new Orquestra3_SIAD.Orquestra_Instance.AttachFile02RequestBody();
            inValue.Body.Token = Token;
            inValue.Body.CodFlowExecute = CodFlowExecute;
            inValue.Body.DsFlowElementAlias = DsFlowElementAlias;
            inValue.Body.DsFileName = DsFileName;
            inValue.Body.DsFilePath = DsFilePath;
            inValue.Body.DsResume = DsResume;
            inValue.Body.RequesterCanSee = RequesterCanSee;
            Orquestra3_SIAD.Orquestra_Instance.AttachFile02Response retVal = ((Orquestra3_SIAD.Orquestra_Instance.InstanceSoap)(this)).AttachFile02(inValue);
            return retVal.Body.AttachFile02Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Orquestra3_SIAD.Orquestra_Instance.AddMessage01Response Orquestra3_SIAD.Orquestra_Instance.InstanceSoap.AddMessage01(Orquestra3_SIAD.Orquestra_Instance.AddMessage01Request request) {
            return base.Channel.AddMessage01(request);
        }
        
        public System.Xml.Linq.XElement AddMessage01(string Token, int CodFlowExecuteTask, string DsMessage, bool RequesterCanSee) {
            Orquestra3_SIAD.Orquestra_Instance.AddMessage01Request inValue = new Orquestra3_SIAD.Orquestra_Instance.AddMessage01Request();
            inValue.Body = new Orquestra3_SIAD.Orquestra_Instance.AddMessage01RequestBody();
            inValue.Body.Token = Token;
            inValue.Body.CodFlowExecuteTask = CodFlowExecuteTask;
            inValue.Body.DsMessage = DsMessage;
            inValue.Body.RequesterCanSee = RequesterCanSee;
            Orquestra3_SIAD.Orquestra_Instance.AddMessage01Response retVal = ((Orquestra3_SIAD.Orquestra_Instance.InstanceSoap)(this)).AddMessage01(inValue);
            return retVal.Body.AddMessage01Result;
        }
    }
}
